# Generated by Django 2.2.4 on 2019-09-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('rating', models.IntegerField(choices=[(0, 'NR-Not Rated'), (1, 'G-General Audience'), (2, 'PG-Parental Guidance'), (3, 'ADULT-Adult Audience')], default=0)),
                ('plot', models.TextField()),
                ('year', models.DateField()),
                ('runtime', models.PositiveIntegerField()),
                ('website', models.URLField()),
            ],
        ),
    ]
