# Generated by Django 2.2.4 on 2019-09-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=28)),
                ('Plot', models.TextField()),
                ('Year', models.PositiveIntegerField()),
                ('Rating', models.IntegerField(choices=[(0, 'NR - Not Rated'), (1, 'G - General'), (2, 'PG - Parental Guidance'), (3, 'R - Restricted')], default=0)),
                ('Runtime', models.IntegerField()),
                ('Website', models.URLField(blank=True)),
            ],
        ),
    ]
